#!/usr/bin/env bash
# A script that transfers a file from our client to a server

if [ $# -lt 3 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi


file="$1"
ip="$2"
username="$3"
SSH_KEY="$4"

scp -o StrictHostKeyChecking=no -i "$SSH_KEY" "$file" "$username"@:"$ip"~/

