#!/usr/bin/env bash
# A Bash script that Install nginx and make listen on port 80
# Serve a web-page that would return a Hello World string

sudo apt-get update -y

sudo apt-get install nginx -y

sudo ufw allow 'Nginx HTTP'

sudo service nginx start

sudo cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

echo -e "Hello World!" | dd status=none of=/var/www/html/index.nginx-debian.html

sudo service nginx restart
