#!/usr/bin/env bash
# This configures a brand new Ubuntu machine to these requirements below
# Configure Nginx so that its HTTP response contains a custom header
# x-served-by and the value of the header should be the hostname of the server

#!/usr/bin/env bash
# A Bash script that Install nginx and make listen on port 80
# Serve a web-page that would return a Hello World string

sudo apt-get update -y

sudo apt-get install nginx -y

sudo ufw allow 'Nginx HTTP'

sudo service nginx start

sudo cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

echo -e "Hello World!" | dd status=none of=/var/www/html/index.nginx-debian.html

redirection="\n\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}"
replace="server_name _";
sed -i "/$replace/a \ $redirection" /etc/nginx/sites-available/default

echo "Ceci n'est pas une page" >> /var/www/html/error_404.html
sudo sed -i '25i\	error_page 404 /error_404.html;' /etc/nginx/sites-available/default

new_header="\t\tadd_header  X-Served-By  \"$(hostname)\" always;"

sed -i "/^\s\+try_files/a \ $new_header" /etc/nginx/sites-available/default

sudo service nginx restart
