#!/usr/bin/env bash
#Displays the username user id and Home directory path for the user form the file /etc/passwd.
file="/etc/passwd"

if [ -e "$file" ]; then
  while IFS=":" read -r username password uid group_id user_info home command; do
    echo "The user $username is part of the $group_id gang, lives in $home and rides $command. $uid's place is protected by the passcode $password, more info about the user here: $user_info"
  done < "$file"
fi
