#!/usr/bin/env bash
# Changes hosts file and:
# Makes localhost resolves to 127.0.0.2 And facebook.com resolves to 8.8.8.8.
cp /etc/hotst ~hosts.new
sed -i 's/127.*localhost$/127.0.0.2\tlocalhost\n8.8.8.8\tfacebook.com/' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
