#!/usr/bin/env bash
# Runs nginx as the nginx user
service apache2 stop
chmod 644 /etc/nginx/nginx.conf
sed -Ei 's/\s*#?\s*user .*/user nginx;/' /etc/nginx/nginx.conf
sed -Ei "s/(listen (\[::\]:)?80) /\180 /" /etc/nginx/sites-enabled/default
sudo -u nginx service nginx restart
